### ISSUE TITLE
Annoying Excption [401] while posting online at wordpress.com/xmlrpc.php

### ISSUE THREAD

**Issue by Shahid20** [alexjamesbrown/JoeBlogs#27]
Hi,
I am new to your gorgeous api and when i ran my sample program on my localhost, it went fine but when i used online address to post on my wordpress blog, it generated an error:
An unhandled exception of type 'CookComputing.XmlRpc.XmlRpcFaultException' occurred in CookComputing.XmlRpcV2.dll

Additional information: Server returned a fault exception: [401] Sorry, you are not allowed to publish posts on this site.

Please let me know what could i do to resolve this????????

**Comment by alexjamesbrown** [comment]
Closing
Will correspond on stackoverflow
http://stackoverflow.com/questions/17501974/joeblogs-wordpress-exception-401

**Comment by Shahid20** [comment]
Thanks sir, i appreciate your efforts and great concern you showed! Applauded effort!
