### ISSUE TITLE
Exception code 500 occurred while editing post

### ISSUE THREAD

**Issue by Shahid20** [alexjamesbrown/JoeBlogs#29]
Snapshot:
![post](https://f.cloud.github.com/assets/4085893/775212/aba5699c-e96c-11e2-90cc-f4ba51fc85e9.JPG)

**Comment by alexjamesbrown** [comment]
Read it...
Content title and excerpt are empty.

So i'm guessing the xml you're passing across doesn't contain content, title or except

**Comment by Shahid20** [comment]
ok! I got it thanks! Again Stupidity!

**Comment by alexjamesbrown** [comment]
Please can we open issues for ISSUES with the API
Use stackoverflow for general questions
