### ISSUE TITLE
Incorrect username or password on Windows Azure

### ISSUE THREAD

**Issue by janigorse** [alexjamesbrown/JoeBlogs#34]
Hi,

I have a hosted website on Azure. When I create new  instance of WordPressWrapper, it failes with "Incorrect username or password" error. It works on local machine. Can you have any idea, why this error occurs?

Thanks,
Jani

**Comment by alexjamesbrown** [comment]
Did you ever figure out the problem?
I can only assume your wp credentials were different between your local box and azure?

**Comment by janigorse** [comment]
Hi,

No I didn't figure out. I switched to WP rest api.

Br,
Jani

**Comment by alexjamesbrown** [comment]
Do you have any more info on the REST API you're using?

**Comment by janigorse** [comment]
http://developer.wordpress.com/docs/api/

I access these api calls through HttpWebRequest and then mapped the response to DataContractJsonSerializer.

Br,
Jani

**Comment by alexjamesbrown** [comment]
Is this for a site hosted on Wordpress.com...?

endpoint seems to be:

https://public-api.wordpress.com/rest/v1/sites/$site/posts/

**Comment by janigorse** [comment]
Yes, that is exactly what I needed for my blooki.st project.

**Comment by alexjamesbrown** [comment]
I'm confused, where did the Azure requirement (the title of this issue) come from?

**Comment by janigorse** [comment]
Sorry for the late answer: blooki.st is hosted on windows azure, thats why I mention it in the title of this issue.

**Comment by alexjamesbrown** [comment]
Ahh ok, so the app on Azure is a .net app, calling a hosted wordpress site?
Sorry, I thought you meant the Wordpress installation was on Azure.

**Comment by janigorse** [comment]
Excatly, I just wanted to add a functionality for a user, that it can import his wordpress blog to blooki.st. Application is actualy a MVC web site.
