### ISSUE TITLE
Invalid Username/Password when Editing Page

### ISSUE THREAD

**Issue by MattyBearBytes** [alexjamesbrown/JoeBlogs#39]
Adding a page is fine, however, when I call EditPage I get the following.

Server returned a fault exception: [403] Incorrect username or password.

Server is reporting that the username that it is receiving is actually what the password is.

When I inspect WordpressWrapper (EditPage method) I can see the correct Username and Password being passed in.

**Comment by MattyBearBytes** [comment]
Appears that the RPC params for EditPost are in the wrong order... assuming that the order matters in the following documentation
http://codex.wordpress.org/XML-RPC_wp#wp.editPage

Will test theory and submit patch if so

**Comment by arlair** [comment]
Thanks, I came across the same issue and your fix works for me.

**Comment by alexjamesbrown** [comment]
Feel free to submit a pull request with any fix...

**Comment by alexjamesbrown** [comment]
Sorry...  i missed that you had already!

Merged.

Thanks
