### ISSUE TITLE
Is this Project active at all? 

### ISSUE THREAD

**Issue by theShiva** [alexjamesbrown/JoeBlogs#46]
Hello,

I would like to know if you are planning on keeping this project active and/or up to date. 

Please let us know.

A working functioning .Net wrapper around Wordpress API is much needed in the community.

Thank you!
-Shiva

**Comment by alexjamesbrown** [comment]
I've not had time to maintain it recently;
That being said, the wp-api (RESTful api) looks promising -

http://v2.wp-api.org/

I think this will eventually replace the wordpress xml-rpc - so I'm not sure how much life JoeBlogs would have left in it?

I would be keen on maintaining this library, however, if I had the time

**Comment by Joe118** [comment]
Eh someone beat me to it :)

Being able to set ALL attributes of a post would be really awesome.

And yeah wp-api looks cool!

**Comment by theShiva** [comment]
Thanks for replying @alexjamesbrown ! Your project was very useful to me 2 years ago when I was trying to build a MVC web app to post to wordpress.
