### ISSUE TITLE
Posting problems with multiple Threads

### ISSUE THREAD

**Issue by ghost** [alexjamesbrown/JoeBlogs#54]
Hi,

I use this library to post into selfhosted wordpress blogs and such hosted on wordpress.com.

With blogs on wordpress.com, in a multi threaded posting environment, it seems that the posting is

1. not thread safe and / or
1. gives unwanted results

in the form of posting multiple articles into the same blog although the individual wrapper object is initialized per blog with its own specific article (Post).

Maybe the problem is wordpress.com itself, as it seems that you can not login into multiple blogs at the same time on the same PC (which is what the application tries to do in fact).

A possible solution for that would be a "logout" function if that exists?

For selfhosted wordpress blogs the problem does not occur.

**Comment by alexjamesbrown** [comment]
This hasn't been maintained in a few years unfortunately -
Now that Wordpress offers a REST api, it's probably easier to communicate with it using that.

**Comment by ghost** [comment]
Yeah, I saw that, thanks.

But I did not find any useful examples or wrappers for C# yet. I just need basic functions like

- Connect to a Blog
- Get Categories
- Create a Post (with Title, Body, Tags, Categories)
- Get the Post URL

Is there anything you might suggest maybe?

**Comment by alexjamesbrown** [comment]
Not that I can think of as a 'wrapper'

I would perhaps just look at using HTTPClient to communicate with the wp REST endpoints directly, depending on what you need to do
